apiVersion: apps/v1
kind: Deployment
metadata:
  name: diary-frontend
  namespace: diary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diary-frontend
  template:
    metadata:
      labels:
        app: diary-frontend
    spec:
      containers:
        - name: web
          image: diary-frontend:4.0
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: diary-frontend
  namespace: diary
spec:
  selector:
    app: diary-frontend
  type: NodePort   # 👈 make service externally accessible
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080   # 👈 fixed port (optional, else Kubernetes assigns one)
