apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diary-ingress
  namespace: diary
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: diary.local
      http:
        paths:
          # Frontend static files
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: diary-frontend
                port:
                  number: 80
          # Backend API
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: diary-backend
                port:
                  number: 8000
